apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argentor.fullname" . }}-gateway
  labels:
    {{- include "argentor.labels" . | nindent 4 }}
data:
  RUST_LOG: {{ .Values.config.logLevel | quote }}
  ARGENTOR_BIND: {{ .Values.config.bind | quote }}
